// "Browse packs from consensustrivia.com" UI on the setup screen.
//
// PACK_CATALOG is regenerated by scrape_packs.py — see CLAUDE.md. Re-run
// the scraper when consensustrivia.com adds new packs.
//
// fetchWithFallback walks a list of attempts (direct, then proxies). Direct
// usually works because consensustrivia.com serves PDFs with permissive
// CORS; the proxies stay in the chain for environments where it's blocked
// (e.g., loaded from file:// or via a strict captive portal).

import { escapeHtml } from '../util/escape.js';
import { looksLikePdfOrZip } from '../parser/zip.js';
import { parsePdf, processZipBuffer } from '../loader.js';

export const PACK_CATALOG = [
  // Post-Secondary
  { level: 'post-secondary', season: '2024-25', tournament: 'Late Fall Tournament', dir: '2025-t1-ps', filePrefix: 'Consensus 2024-25 T1 PS', packCount: 10 },
  { level: 'post-secondary', season: '2024-25', tournament: 'Qualifier', dir: '2025-t2-ps', filePrefix: 'Consensus 2024-25 T2 PS', packCount: 11 },
  { level: 'post-secondary', season: '2024-25', tournament: 'Championship', dir: '2025-t3-ps', filePrefix: 'Consensus 2024-25 T3 PS', packCount: 18 },
  { level: 'post-secondary', season: '2023-24', tournament: 'Late Fall Tournament', dir: '2024-t2-ps', filePrefix: 'Consensus 2023-24 T2 PS', packCount: 10 },
  { level: 'post-secondary', season: '2023-24', tournament: 'Qualifier', dir: '2024-t3-ps', filePrefix: 'Consensus 2023-24 T3 PS', packCount: 11 },
  { level: 'post-secondary', season: '2023-24', tournament: 'Championship', dir: '2024-t4-ps', filePrefix: 'Consensus 2023-24 T4 PS', packCount: 11 },
  { level: 'post-secondary', season: '2023-24', tournament: 'Summer Open', dir: '2024-t1-open', filePrefix: 'Consensus 2023-24 T1 PS', packCount: 10 },
  { level: 'post-secondary', season: '2022-23', tournament: 'Season Opener', dir: '2023-t1-ps', filePrefix: 'Consensus 2022-23 T1 PS', packCount: 10 },
  { level: 'post-secondary', season: '2022-23', tournament: 'Winter Tournament', dir: '2023-t2-ps', filePrefix: 'Consensus 2022-23 T2 PS', packCount: 10 },
  { level: 'post-secondary', season: '2022-23', tournament: 'Summer Open', dir: '2023-t3-open', filePrefix: 'Consensus 2022-23 T3 PS', packCount: 11 },
  // High School
  { level: 'high-school', season: '2024-25', tournament: 'Late Fall Tournament (Junior)', dir: '2025-t1-jr', filePrefix: 'Consensus 2024-25 T1 JR', packCount: 10 },
  { level: 'high-school', season: '2024-25', tournament: 'Late Fall Tournament', dir: '2025-t1-hs', filePrefix: 'Consensus 2024-25 T1 HS', packCount: 10 },
  { level: 'high-school', season: '2024-25', tournament: 'Qualifier (B)', dir: '2025-t2-hs-b', filePrefix: 'Consensus 2024-25 T2 HS B', packCount: 10 },
  { level: 'high-school', season: '2024-25', tournament: 'Qualifier', dir: '2025-t2-hs', filePrefix: 'Consensus 2024-25 T2 HS', packCount: 11 },
  { level: 'high-school', season: '2024-25', tournament: 'Championship', dir: '2025-t3-hs', filePrefix: 'Consensus 2024-25 T3 HS', packCount: 18 },
  { level: 'high-school', season: '2023-24', tournament: 'Season Opener (Junior)', dir: '2024-t1-jr', filePrefix: 'Consensus 2023-24 T1 JR', packCount: 10 },
  { level: 'high-school', season: '2023-24', tournament: 'Season Opener', dir: '2024-t1-hs', filePrefix: 'Consensus 2023-24 T1 HS', packCount: 10 },
  { level: 'high-school', season: '2023-24', tournament: 'Late Fall Tournament', dir: '2024-t2-hs', filePrefix: 'Consensus 2023-24 T2 HS', packCount: 10 },
  { level: 'high-school', season: '2023-24', tournament: 'Qualifier', dir: '2024-t3-hs', filePrefix: 'Consensus 2023-24 T3 HS', packCount: 11 },
  { level: 'high-school', season: '2023-24', tournament: 'Championship', dir: '2024-t4-hs', filePrefix: 'Consensus 2023-24 T4 HS', packCount: 15 },
  { level: 'high-school', season: '2022-23', tournament: 'Season Opener', dir: '2023-t1-hs', filePrefix: 'Consensus 2022-23 T1 HS', packCount: 10 },
  { level: 'high-school', season: '2022-23', tournament: 'Winter Qualifier', dir: '2023-t2-hs', filePrefix: 'Consensus 2022-23 T2 HS', packCount: 10 },
  { level: 'high-school', season: '2022-23', tournament: 'Championship', dir: '2023-t3-hs', filePrefix: 'Consensus 2022-23 T3 HS', packCount: 12 },
];

const PACK_SITE_BASE = 'https://www.consensustrivia.com';
const IS_LOCAL_SERVER = location.protocol === 'http:' && (location.hostname === 'localhost' || location.hostname === '127.0.0.1');
// Public proxies are ordered by observed reliability for consensustrivia.com
// pack PDFs: codetabs has been the fastest/most consistent in practice.
const CORS_PROXIES = [
  ...(IS_LOCAL_SERVER ? [(url) => `${location.origin}/proxy/${encodeURIComponent(url)}`] : []),
  (url) => `https://api.codetabs.com/v1/proxy/?quest=${encodeURIComponent(url)}`,
  (url) => `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
  (url) => `https://corsproxy.io/?${encodeURIComponent(url)}`,
  (url) => `https://thingproxy.freeboard.io/fetch/${url}`,
];

function packPdfUrl(t, n) {
  return `${PACK_SITE_BASE}/${t.level}/packs/${t.dir}/${t.filePrefix} Pack ${n}.pdf`;
}
function packZipUrl(t) {
  return `${PACK_SITE_BASE}/${t.level}/packs/${t.dir}/${t.filePrefix} Packs.zip`;
}

async function fetchWithFallback(url, statusEl) {
  const ATTEMPT_TIMEOUT_MS = 12000;
  const directAttempt = { label: 'direct', fn: (signal) => fetch(url, { signal }) };
  const proxyAttempts = CORS_PROXIES.map((makeProxy, i) => ({
    label: i === 0 && IS_LOCAL_SERVER ? 'local proxy' : `proxy ${i + (IS_LOCAL_SERVER ? 0 : 1)}`,
    fn: (signal) => fetch(makeProxy(url), { signal }),
  }));
  const attempts = [directAttempt, ...proxyAttempts];
  for (const attempt of attempts) {
    if (statusEl) statusEl.textContent = `Downloading via ${attempt.label}...`;
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), ATTEMPT_TIMEOUT_MS);
    try {
      const r = await attempt.fn(ctrl.signal);
      if (!r.ok) continue;
      const buffer = await r.arrayBuffer();
      if (looksLikePdfOrZip(buffer)) return buffer;
    } catch (e) { /* try next */ } finally {
      clearTimeout(timer);
    }
  }
  throw new Error('All download attempts failed (CORS blocked). Run this page from a local web server (e.g. `python -m http.server`) or download the pack manually from consensustrivia.com and upload it.');
}

let activeBrowserLevel = 'post-secondary';

function renderBrowser() {
  const container = document.getElementById('browser-content');
  if (!container) return;
  const tournaments = PACK_CATALOG.filter(t => t.level === activeBrowserLevel);
  const bySeason = {};
  for (const t of tournaments) {
    if (!bySeason[t.season]) bySeason[t.season] = [];
    bySeason[t.season].push(t);
  }
  const seasons = Object.keys(bySeason).sort().reverse();
  const html = seasons.map(season => {
    const rows = bySeason[season].map((t) => {
      const tIdx = PACK_CATALOG.indexOf(t);
      const packBtns = [];
      for (let n = 1; n <= t.packCount; n++) {
        packBtns.push(`<button class="browser-pack-btn" data-action="pack" data-tidx="${tIdx}" data-pack="${n}" title="Pack ${n}">${n}</button>`);
      }
      const zipBtn = `<button class="browser-pack-btn zip" data-action="zip" data-tidx="${tIdx}" title="Download all packs as zip">All ZIP</button>`;
      return `
        <div class="browser-tournament">
          <div class="browser-tournament-name">${escapeHtml(t.tournament)}</div>
          <div class="browser-tournament-actions">${packBtns.join('')}${zipBtn}</div>
        </div>`;
    }).join('');
    return `<div class="browser-season"><div class="browser-season-label">${escapeHtml(season)} Season</div>${rows}</div>`;
  }).join('');
  container.innerHTML = html || '<div style="color:#666;font-size:0.9rem;">No tournaments available.</div>';
}

export function setupPackBrowser() {
  const toggle = document.getElementById('browse-toggle');
  if (toggle) {
    toggle.addEventListener('click', () => {
      const browser = document.getElementById('pack-browser');
      const opening = !browser.classList.contains('open');
      browser.classList.toggle('open', opening);
      toggle.textContent = opening
        ? 'Hide online pack browser'
        : 'Or browse packs from consensustrivia.com';
      if (opening) renderBrowser();
    });
  }

  document.querySelectorAll('.browser-tab').forEach(tab => {
    tab.addEventListener('click', () => {
      activeBrowserLevel = tab.dataset.level;
      document.querySelectorAll('.browser-tab').forEach(t => t.classList.toggle('active', t === tab));
      renderBrowser();
    });
  });

  const content = document.getElementById('browser-content');
  if (content) {
    content.addEventListener('click', async (e) => {
      const btn = e.target.closest('.browser-pack-btn');
      if (!btn) return;
      const action = btn.dataset.action;
      const tIdx = parseInt(btn.dataset.tidx, 10);
      const tournament = PACK_CATALOG[tIdx];
      if (!tournament) return;
      const allBtns = document.querySelectorAll('.browser-pack-btn');
      allBtns.forEach(b => b.disabled = true);
      const statusEl = document.getElementById('pdf-status');
      try {
        if (action === 'pack') {
          const n = parseInt(btn.dataset.pack, 10);
          const url = packPdfUrl(tournament, n);
          if (statusEl) {
            statusEl.textContent = `Downloading Pack ${n}...`;
            statusEl.className = 'pdf-status';
          }
          const buffer = await fetchWithFallback(url, statusEl);
          const sel = document.getElementById('zip-pack-select');
          if (sel) sel.style.display = 'none';
          await parsePdf(buffer, `${tournament.filePrefix} Pack ${n}.pdf`);
        } else if (action === 'zip') {
          const url = packZipUrl(tournament);
          if (statusEl) {
            statusEl.textContent = `Downloading ${tournament.tournament} zip...`;
            statusEl.className = 'pdf-status';
          }
          const buffer = await fetchWithFallback(url, statusEl);
          await processZipBuffer(buffer);
        }
      } catch (err) {
        if (statusEl) {
          statusEl.textContent = 'Error: ' + err.message;
          statusEl.className = 'pdf-status error';
        }
      } finally {
        allBtns.forEach(b => b.disabled = false);
      }
    });
  }
}
